---
dns:
  default_forwarders:
  # Public OpenDNS Resolvers
  - 208.67.222.222
  - 208.67.220.220
  zones:
  - domain: internal-domain
    forwarders:
    # Datacenter Test
    - 172.17.0.2
    # Internal DCs
    - 192.168.0.2
    - 192.168.0.3
  - domain: internal-prod-domain.net
    forwarders:
    # AWS Production Bind Servers
    - 10.0.0.9
    - 10.0.1.9
  - domain: internal-test-domain.net
    forwarders:
    # AWS Test Bind Servers
    - 10.10.0.9
    - 10.10.1.9
  - domain: amazonaws.com
    forwarders:
    # Forward requests for amazonaws.com
    # AWS Production Bind Servers
    - 10.0.0.9
    - 10.0.1.9
  - domain: elasticbeanstalk.com
    forwarders:
    # Forward requests for elasticbeanstalk.com
    # AWS Production Bind Servers
    - 10.0.0.9
    - 10.0.1.9
